version: 2

models:
  - name: films
    description: "This table contains details about films"
    columns:
      - name: film_id
        description: "Unique identifier for the film"
        tests:
          - unique
          - not_null
      - name: title
        description: "Title of the film"
        tests:
          - not_null
      - name: release_date
        description: "Release date of the film"
        tests:
          - not_null
      - name: price
        description: "Price of ticket"
        tests:
          - not_null
      - name: rating
        description: "MPAA rating of the film"
        tests:
          - not_null
      - name: user_rating
        description: "User rating of the film"
        tests:
          - not_null

  - name: actors
    description: "This table contains details about actors"
    columns:
      - name: actor_id
        description: "Unique identifier for the actor"
        tests:
          - unique
          - not_null
      - name: name
        description: "First name of the actor"
        tests:

  - name: film_actors
    description: "This table maps films to the actors that starred in them"
    columns:
      - name: film_id
        description: "Unique identifier for the film"
        tests:
          - not_null
      - name: actor_id
        description: "Unique identifier for the actor"
        tests:
          - not_null

  - name: film_ratings
    description: "This model aggregates film data and calculates the average rating of each film"
    columns:
      - name: film_id
        description: "Unique identifier for the film"
        tests:
          - unique
          - not_null
      - name: title
        description: "Title of the film"
        tests:
          - not_null
      - name: release_date
        description: "Release date of the film"
        tests:
          - not_null
      - name: price
        description: "Price of ticket"
        tests:
          - not_null
      - name: rating
        description: "MPAA rating of the film"
      - name: user_rating
        description: "Average user rating of the film"
        tests:
          - not_null
      - name: actor_count
        description: "Number of actors in the film"
        tests:
          - not_null
      - name: avg_actor_rating
        description: "Average rating of films that the actors in the film have acted in"
        tests:
          - not_null